import requests
import csv
import io

# Official Data URLs
URL_HALTESTELLEN = "https://data.wien.gv.at/csv/wienerlinien-ogd-haltestellen.csv"
URL_STEIGE = "https://data.wien.gv.at/csv/wienerlinien-ogd-steige.csv"
URL_LINIEN = "https://data.wien.gv.at/csv/wienerlinien-ogd-linien.csv"

def download_csv(url):
    print(f"Downloading {url}...")
    r = requests.get(url)
    r.raise_for_status()
    r.encoding = 'utf-8' # Force UTF-8
    return list(csv.DictReader(io.StringIO(r.text, newline=None), delimiter=';'))

def main():
    try:
        haltestellen = download_csv(URL_HALTESTELLEN)
        steige = download_csv(URL_STEIGE)
        linien = download_csv(URL_LINIEN)
        
        if linien:
            print(f"Linien Keys: {list(linien[0].keys())}")
            # return # Uncomment to stop and check
    except Exception as e:
        print(f"Error downloading data: {e}")
        return

    # 1. Map Line ID -> Line Name (e.g., 'U1')
    # Filter for Metro (ptMetro) first to keep it manageable, or all?
    # User asked for "all stations". Let's try to include Metro, Tram, Bus.
    # But let's prioritize Metro for the name sorting.
    
    valid_lines = {}
    for l in linien:
        # ECHTZEIT=1 means it has realtime data
        if l['ECHTZEIT'] == '1':
            valid_lines[l['LINIEN_ID']] = {
                'name': l['BEZEICHNUNG'],
                'type': l['VERKEHRSMITTEL']
            }

    # 2. Map Stop ID -> Stop Name
    stops_map = {h['HALTESTELLEN_ID']: h['NAME'] for h in haltestellen}

    # 3. Group RBLs by Station+Line
    # Key: "Station Name (Line Name)" -> Set of RBLs
    grouped_stops = {}

    for s in steige:
        line_id = s['FK_LINIEN_ID']
        stop_id = s['FK_HALTESTELLEN_ID']
        rbl = s['RBL_NUMMER']
        
        if line_id in valid_lines and stop_id in stops_map and rbl:
            line_info = valid_lines[line_id]
            stop_name = stops_map[stop_id]
            
            # Create a display name like "Stephansplatz (U1)"
            # For buses/trams, maybe just "Station Name (Line)"
            display_name = f"{stop_name} ({line_info['name']})"
            
            if display_name not in grouped_stops:
                grouped_stops[display_name] = set()
            grouped_stops[display_name].add(rbl)

    # 4. Convert to list and sort
    output_list = []
    for name, rbls in grouped_stops.items():
        # Join RBLs with comma
        rbl_str = ",".join(sorted(list(rbls)))
        output_list.append({'id': rbl_str, 'name': name})

    # Sort by name
    output_list.sort(key=lambda x: x['name'])

    # 5. Write to stops_data.py
    print(f"Found {len(output_list)} stops.")
    with open('stops_data.py', 'w', encoding='utf-8') as f:
        f.write("# Generated by import_data.py\n")
        f.write("# Full list of Wiener Linien stops with Realtime data\n\n")
        f.write("STOPS = [\n")
        for s in output_list:
            f.write(f"    {{'id': '{s['id']}', 'name': '{s['name']}'}},\n")
        f.write("]\n")
    
    print("Done! stops_data.py updated.")

if __name__ == '__main__':
    main()
